## mysql
# FlattrMap
CREATE TABLE DB_TABLE_PREFIXFlattrMap(
 DB_COLUMN_PREFIXitemId int(11) NOT NULL,
 DB_COLUMN_PREFIXitemValue varchar(128),
 PRIMARY KEY(DB_COLUMN_PREFIXitemId)
) DB_TABLE_TYPE
/*!40100 DEFAULT CHARACTER SET utf8 */;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FlattrMap', 1, 0);

## postgres
# FlattrMap
CREATE TABLE DB_TABLE_PREFIXFlattrMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR(128)
);

ALTER TABLE DB_TABLE_PREFIXFlattrMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FlattrMap', 1, 0);

## oracle
# FlattrMap
CREATE TABLE DB_TABLE_PREFIXFlattrMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR2(128)
);

ALTER TABLE DB_TABLE_PREFIXFlattrMap
 ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId)
;

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FlattrMap', 1, 0);

## db2
# FlattrMap
CREATE TABLE DB_TABLE_PREFIXFlattrMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue VARCHAR(128)
);

ALTER TABLE DB_TABLE_PREFIXFlattrMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FlattrMap', 1, 0);

## mssql
# FlattrMap
CREATE TABLE DB_TABLE_PREFIXFlattrMap(
 DB_COLUMN_PREFIXitemId INT NOT NULL,
 DB_COLUMN_PREFIXitemValue NVARCHAR(128) NULL
);

ALTER TABLE DB_TABLE_PREFIXFlattrMap ADD PRIMARY KEY (DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FlattrMap', 1, 0);

## sqlite
# FlattrMap
CREATE TABLE DB_TABLE_PREFIXFlattrMap(
 DB_COLUMN_PREFIXitemId INTEGER NOT NULL,
 DB_COLUMN_PREFIXitemValue TEXT
);

CREATE UNIQUE INDEX DB_TABLE_PREFIXFlattrMap_pkey ON DB_TABLE_PREFIXFlattrMap(DB_COLUMN_PREFIXitemId);

INSERT INTO DB_TABLE_PREFIXSchema (
 DB_COLUMN_PREFIXname,
 DB_COLUMN_PREFIXmajor,
 DB_COLUMN_PREFIXminor
) VALUES('FlattrMap', 1, 0);

